id: A49A2AA43
title: fB87A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:38.236413
  last_modified_at: 2022-05-27 15:20:38.236416
