id: A49A2AA43
title: f677B
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:38.105791
  last_modified_at: 2022-05-27 15:20:38.105793
