id: A49A2AA43
title: f28DA
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:37.849976
  last_modified_at: 2022-05-27 15:20:37.849978
