id: A49A2AA43
title: f7242
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:38.129069
  last_modified_at: 2022-05-27 15:20:38.129072
