id: A49A2AA43
title: fF20A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:38.351322
  last_modified_at: 2022-05-27 15:20:38.351325
