id: A49A2AA43
title: f8D9D
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:38.179799
  last_modified_at: 2022-05-27 15:20:38.179802
