id: A49A2AA43
title: f41C0
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:37.903155
  last_modified_at: 2022-05-27 15:20:37.903158
