id: A49A2AA43
title: f6D79
type: translation
source_metadata:
  languages:
  - sa
  - en
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:20:38.127635
  last_modified_at: 2022-05-27 15:20:38.127637
